from pydantic import BaseModel
from typing import List, Dict, Optional
import json
import os

PATIENTS_FILE = "data/patients.json"

def load_patients_from_file():
    if os.path.exists(PATIENTS_FILE):
        with open(PATIENTS_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
            # حول كل dict إلى PatientHistory object
            return [PatientHistory(**p) for p in data]
    return []

def save_patients_to_file():
    with open(PATIENTS_FILE, "w", encoding="utf-8") as f:
        json.dump([p.dict() for p in patients_db], f, ensure_ascii=False, indent=2)

class PatientHistory(BaseModel):
    id: Optional[str] = None
    name: str
    age: int
    gender: str
    marital_status: Optional[str] = None
    occupation: Optional[str] = None
    address: Optional[str] = None
    source_info: Optional[str] = None

    # Chief Complaint
    chief_complaint: str
    complaint_duration: str
    # HOPI (سرد الأعراض الأساسية والمتفرعة)
    hopi: List[Dict]
    # ROS (مراجعة الأنظمة)
    ros: Dict[str, str]

    # Past History
    chronic_diseases: List[str]
    surgeries: List[str]
    allergies: List[str]
    medications: List[str]
    previous_admissions: List[str]

    # Family History
    similar_conditions: List [str]
    chronic_diseases_family: List[str]
    consanguinity: bool

    # Social History
    smoking: bool
    stimulants: List [str]
    alcohol: bool 
    housing: Optional[str] = None
    pets: List [str]
    travel: bool

    # Immunization
    immunizations: Optional[List[str]] = []

    # Gyn/Obs (اختياري)
    gyn_obs: Optional[Dict[str, str]] = {}

    # Nutrition/Developmental (للأطفال)
    nutrition: Optional[Dict[str, str]] = {}
    development: Optional[Dict[str, str]] = {}

    # Special symptoms (حسب الجهاز)
    system_specific: Optional[Dict[str, List[str]]] = {}

    # Auto-generated by AI
    visit_time: Optional[str] = None
    status: Optional[str] = ""
    notes: Optional[str] = ""
    ai_summary: Optional[str] = ""
    doctor_ai_summary: Optional[str] = ""
    icd11: Optional[str] = ""
    icd11_desc: Optional[str] = ""
    red_flags: Optional[List[str]] = []
    recommendations: Optional[List[str]] = []

    past_history: Optional[dict] = None
    family_history: Optional[dict] = None
    social_history: Optional[dict] = None
    gyn_obs: Optional[dict] = None
    child_history: Optional[dict] = None
    labs: Optional[List[str]] = []

# عند بداية التشغيل: حمّل المرضى من الملف
patients_db: List[PatientHistory] = load_patients_from_file()